name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Setup Rust
        run: |
          rustup update stable
          rustup default stable
          rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.101 --locked --force

      - uses: oven-sh/setup-bun@v2

      - name: Cargo fmt (check)
        run: cargo fmt --all -- --check

      - name: Build WASM package
        run: make build

      - name: Example tests
        working-directory: example
        run: |
          bun install
          bun test
